### ISSUE TITLE
Make calendar popup below bar as before

### ISSUE THREAD

**Issue by IvanMalison** [taffybar/taffybar#261]
See https://github.com/travitch/taffybar/issues/255#issuecomment-374132729

**Comment by teleshoes** [comment]
@IvanMalison 
also, for me, calendar opens half-hidden the first time you open it after restarting taffybar:
![calendar_first_open](https://user-images.githubusercontent.com/592062/39851418-a9d08a88-53e4-11e8-918d-8390b0b55b66.png)

opening again looks like normal, though still without avoiding struts:
![calendar_second_open](https://user-images.githubusercontent.com/592062/39851419-ae8f88da-53e4-11e8-9b7f-d4c48f3752bf.png)

**Comment by teleshoes** [comment]
@IvanMalison calendar still opens half-hidden for me, the first time you open it after starting taffybar (closing calendar and reopening it works)

**Comment by IvanMalison** [comment]
@u11gh Can you comment?

**Comment by u11gh** [comment]
I'm not sure what "half-hidden" means.  Does the calendar window cover
taffybar?  Or is part of the calendar window invisible (either covered
by another window or outside the screen)?

@teleshoes Could you please provide a screenshot?

**Comment by IvanMalison** [comment]
for me, the calendar spawns just above the taffybar window atm

**Comment by teleshoes** [comment]
@u11gh it still looks exactly the same as my previous screenshots above.

my calendar is right-aligned on my taffybar. the first time i open the calendar, sunday-wednesday show up, and thursday-saturday are cut off (at the edge of the screen) and not visible. the first screenshot is the topright corner of my monitor, with the calendar half-showing like this.
closing the calendar and reopening it show up correctly, as in the second screenshot i provided above.
(if i restart taffybar, it will show up wrong exactly once, and then be correct until i restart)

**Comment by u11gh** [comment]
@teleshoes Thanks for clarifying

So the calendar does not hide taffybar anymore.  Good.  Vertical
placement works correctly. That's what has been fixed with #261.

The horizontal placement problem that you describe still needs to be
fixed.  When I try to reproduce that behaviour I see the opposite
effect: The first click on a clock that is placed at the right edge will
open the calendar shifted to the left like this:
![taffybar#261](https://user-images.githubusercontent.com/23435626/57875457-4e025c00-7813-11e9-826a-21204aa5091a.png)

I shall have a look at that.

**Comment by teleshoes** [comment]
@u11gh thanks!

p.s. ...actually vertical is still broken for me with `c33f6785`.
it still covers taffybar instead of appearing beneath it, completely covering the clock widget

**Comment by IvanMalison** [comment]
@u11gh @teleshoes Vertical placement does seem to be fixed for me, but I remember looking at this when @teleshoes originally commented that it wasn't fixed and seeing that it WAS covering the bar. @teleshoes can you still repro?

**Comment by teleshoes** [comment]
yea, both horizontal and vertical placement are wrong the first time, and vertical is wrong every time.

**Comment by IvanMalison** [comment]
@teleshoes and you're sure you're on the latest git version?

**Comment by teleshoes** [comment]
yes, quite sure. i also tried reinstalling with stack, and even tried it with the taffybar.hs.example just to eliminate any other vars. calendar popup location is broken ootb for me.

**Comment by teleshoes** [comment]
caveat: when i use `taffybar.hs.example`, my bar starts 10px below the top of the screen (barpadding=10), and the calendar only covers 10px of the bar. if i do `example` with no padding, the calendar is placed vertically correctly.

also, in every case, vertical positioning never changes, no matter how many times i open/close the calendar. horizontal positioning does, also in every case, change after the first open/close

**Comment by teleshoes** [comment]
ok, confirmed: for me, vertical placement is working in latest git EXCEPT for barPadding, which it ignores.
if you set the padding to 100px and the height to 50px and the position to top, the calendar will still appear at y=50px, instead of y=250px
`(or, for that matter, y=150px. 150 is wrong, but its what i would expect looking at the code. im confused as to why its not 150, since its using window-get-position and just shifting by requisition height. is windowGetPosition just returning 0 when theres padding? it works for position = bottom tho....oh well)`

IMO, ignoring padding is a very minor bug. the horizontal position problem is much worse.

@IvanMalison

**Comment by IvanMalison** [comment]
@teleshoes you can file a separate issue for padding if you would like.

**Comment by ewolk** [comment]
@IvanMalison i dont care about padding. i care about the horizontal positioning being broken tho, as it hides half the calendar.
is there another ticket i should be following about that one?

**Comment by teleshoes** [comment]
@IvanMalison i dont care about padding. i care about the horizontal positioning being broken tho, as it hides half the calendar.
is there another ticket i should be following about that one?

**Comment by IvanMalison** [comment]
@teleshoes I don't think so. It's not broken with my configuration, so make sure to post a minimal repro.

**Comment by ewolk** [comment]
minimal repro case is just `taffybar.hs.example`

**Comment by teleshoes** [comment]
ticket created. minimal repro case is just `taffybar.hs.example`
