### ISSUE TITLE
Battery widget causes segfaults in ghc 8.4

### ISSUE THREAD

**Issue by nrdxp** [taffybar/taffybar#377]
**Describe the bug**
taffybar is unusable due to very early segfaults after just seconds

**To Reproduce**
start taffybar, do something like move the mouse or change window or workspace, it will crash within seconds. If you don't touch the mouse or do anything it will not crash

**Expected behavior**
expected to function properly. I have a core dump if you would like me to upload it but it is 208MB so let me know on that.

**Version information**
Taffybar version (or git sha if building from source): 2.1.1
Installation method (nix/stack/cabal/arch packages): aur package
Gtk version: 3.22.30

**Comment by IvanMalison** [comment]
@nrdxp looks like you are hitting https://github.com/taffybar/taffybar/issues/358 which is actually a bug in ghc.

As documented in the README, the aur package is not the recommended way to install taffybar. You will have a much more stable experience with a stack or cabal install

See my comments in https://github.com/taffybar/taffybar/issues/151 for the reasoning behind this.

**Comment by IvanMalison** [comment]
@nrdxp @LeifW May be able to help you get things working if you really want to use the aur route.

**Comment by nrdxp** [comment]
neither of these work on my machine, I have tried multiple resolvers with stack and I just don't even know how to begin to debug cabal

**Comment by IvanMalison** [comment]
@nrdxp There is the quick-start script which is intended to setup a stack install. Have you tried that?

What error do you get specifically. I'm happy to help you get things working in https://gitter.im/taffybar/Lobby

**Comment by IvanMalison** [comment]
@nrdxp You need to specify certain extra deps, because no stack resolver has all the necessary packages.

You can see the packages that are needed in:

https://github.com/travitch/taffybar/blob/afbe492d857b336d1398d35218a17de8218cf151/stack.yaml.example#L10

**Comment by LeifW** [comment]
What GHC version are you using? And what taffybar monitors do you have running?

**Comment by nrdxp** [comment]
I am building it with stack right now I already deleted the aur package, thanks for the help I will see how it goes

**Comment by LeifW** [comment]
FWIW the AUR package works fine for me since the ghc in [community] was upgraded from 8.4.2 to 8.4.3. I'm running workspaces, layout, windows, notifications, mpris, clock, battery, mem, cpu, and wifi.

**Comment by weskerfoot** [comment]
I'm seeing this with GHC 8.4.3 now

**Comment by IvanMalison** [comment]
@weskerfoot Don't downgrade, I think @LeifW is saying that things were broken in 8.4.2 and were then fixed in 8.4.3

**Comment by weskerfoot** [comment]
@IvanMalison yeah sorry, I think I misunderstood the issue.

**Comment by LeifW** [comment]
Yes, I had frequent segfaults with GHC 8.4.2 (removing the battery widget seemed to help), and now maybe once or twice a day with GHC 8.4.3. So the suspicion was that it was a bug in the 8.4.2 runtime. I documented what I dug into on #358. Perhaps there is still a bug in GHC 8.4.3? (I didn't see my exact bug mentioned in the release notes of things fixed). If you're using stack you should be able to easily try a different compiler version.

You could also run it as a systemd user service, and tell systemd to restart it on crash (which might help with memory usage if it has a memory leak).

**Comment by LeifW** [comment]
If you provide your taffybar.hs I could see if I could reproduce it (I'm on GHC 8.4.3), else you could strip down widgets in your taffybar.hs to a minimal set and see if the issue goes away.

**Comment by dongcarl** [comment]
This is happening with the default taffybar config for me. Also trying the AUR package.

**Comment by dongcarl** [comment]
All I had to do was `taffybay -l DEBUG`, then switch between my workspaces quickly with mod+1|2|3|4. And it would say:
```
Launching custom binary /home/dongcarl/.cache/taffybar/taffybar-linux-x86_64

fish: “taffybar -l DEBUG” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by LeifW** [comment]
Ok, wow, yes, it definitely segfaults with that config.
I'll try and look into that a bit later.
In the meantime, here's my config: https://gist.github.com/LeifW/1e37c058670a5b6721e5d7b0d8999970
(the wifi part requires the iwlib package, which is available with `pacman -S haskell-iwlib` if you're using haskell packages from [community], or install from hackage otherwise, or just remove that part)
The `-l DEBUG` part doesn't seem to do anything for me (no logs), but just running `taffybar` and switching workspaces around a few times is enough to crash it on GHC 8.4.3. We can look into this more, but in the meantime I might try either stripping down your taffybar.hs, or try a different GHC version - perhaps 8.2.2?

**Comment by LeifW** [comment]
It's not totally crash-free with my taffybar.hs, granted - it segfaults about once per hour of regular use.

**Comment by IvanMalison** [comment]
@dongcarl @LeifW Can we verify that this issue only affects ghc >= 8.4?

**Comment by dongcarl** [comment]
I can verify that it DOES, but not that it ONLY affects ghc >= 8.4
```
~> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.4.3
```

**Comment by weskerfoot** [comment]
@dongcarl @IvanMalison @LeifW 

I was seeing segfaults after switching workspaces a few times as well.

I was using the example config [here](https://github.com/taffybar/taffybar/blob/master/taffybar.hs.example), since my old taffybar.hs seems to be pretty broken with newer versions anyway (it was written way back when it was still on gtk2).

Removing the battery widget solves the issue for me.

**Comment by dongcarl** [comment]
Can confirm that removing the battery widget seems to solve the issue...

**Comment by IvanMalison** [comment]
Okay, reopening this for the exclusive purpose of dealing with the battery segfault in new versions of ghc.

If there are any segfaults that do not involve the battery widget, please open another issue, and link to the discussion here.

**Comment by weskerfoot** [comment]
I've written a systemd user unit that starts taffybar (and restarts it if it crashes)
```
[Unit]
Description=Taffybar
After=graphical.target

[Service]
ExecStart=%h/.cabal/bin/taffybar
Restart=always
RestartSec=2

[Install]
WantedBy=multi.user.target
```

Just place it under `$HOME/.config/systemd/user/taffybar.service`
Then
`systemctl --user enable taffybar.service`
`systemctl start taffybar`
And it should handle restarting it if it crashes as well as starting it up automatically when XMonad is started.

**Comment by IvanMalison** [comment]
```
ExecStart=/usr/bin/env taffybar
```

would be better.

This is what ive always done.

**Comment by LeifW** [comment]
I added a systemd user service file to the taffybar AUR package. It's not really a big deal if taffybar crashes, since it's stateless.

**Comment by weskerfoot** [comment]
Hey, so I'm working on trying to build a version of taffybar that will work with valgrind.

Here's what I tried:
`  ghc-options: -Wall -funbox-strict-fields -fno-warn-orphans -g`
`-g` is supposed to enable debug symbols, but It doesn't seem to compile properly.

Apparently it might also need a GHC compiled with DWARF. Are there any other potential issues here? Does `-fPIC` affect this at all?

**Comment by IvanMalison** [comment]
@weskerfoot One thing you'll need to be aware of is that taffybar recompiles and reexecs itself if you are using dyre taffybar, so the flags need to be passed to dyre, not in the cabal file.

For the purposes of debugging, I would recommend simply using startTaffybar to build a new executable (e.g. my taffybar), avoiding dyre all together.

**Comment by IvanMalison** [comment]
Can anyone reproduce this now that #231 is fixed?

**Comment by IvanMalison** [comment]
@LeifW ^

**Comment by LeifW** [comment]
Yes, unfortunately. I just built from master, and it doesn't seem to have that much of an effect. It was still crashing about once every 10 minutes (depending on use) if I have the battery widget on (Though that's way better than how it was crashing every few seconds under GHC 8.4.2). It hasn't crashed in the past half hour, though. *fingers crossed*

**Comment by IvanMalison** [comment]
@LeifW Any chance you can run with gdb to get a backtrace?

I'll probably look in to this soon, but would be nice if i could verify I am seeing the same hting.

**Comment by LeifW** [comment]
Sure, I'll give that a try. It sometimes takes a while to crash. It seemed to crash quicker with the taffybar.hs.example included in the repo, where the major difference from my config seems to be the `withBatteryRefresh $ withLogServer $ withToggleServer`.
I also get stacktraces on crash when I run it with systemd - would that be good enough, or you want me to run the backtrace command in gdb when it crashes?
These seem to be in different places, but they seem to end in rts/libHSrts_thr-ghc8.4.3.so.
Here's the last stacktrace reported by systemd:
```
Process 1436 (taffybar-linux-) of user 1000 dumped core.
                                              
                                              Stack trace of thread 1436:
                                              #0  0x00007f8f7b23cb2c n/a (/usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so)
                                              #1  0x00007f8f7b23d0e6 n/a (/usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so)
...skipping...
                                              #2  0x00007f8f7b23f8e9 n/a (/usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so)
                                              #3  0x00007f8f7b222b74 n/a (/usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so)
                                              #4  0x00007f8f7b22351e n/a (/usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so)
                                              #5  0x00007f8f7b224b01 scheduleWaitThread (/usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so)
                                              #6  0x00007f8f759e3c92 zdgizmgtkzm3zi0zi23zmJ49TgmeR4Ha3tFtwazzpVcUzdGIziGtkziObjectsziWidgetzdgizzmgtkzzm3zzi0zzi23zzmJ49TgmeR4Ha3tFtwazzzzpVcU>
                                              #7  0x00007f8f79072cf8 n/a (libgtk-3.so.0)
                                              #8  0x00007f8f791c047d n/a (libgtk-3.so.0)
                                              #9  0x00007f8f77581c96 n/a (libgobject-2.0.so.0)
                                              #10 0x00007f8f7759d3a4 g_signal_emit_valist (libgobject-2.0.so.0)
                                              #11 0x00007f8f7759e130 g_signal_emit (libgobject-2.0.so.0)
                                              #12 0x00007f8f791cd503 n/a (libgtk-3.so.0)
                                              #13 0x00007f8f78fa65ff gtk_container_propagate_draw (libgtk-3.so.0)
                                              #14 0x00007f8f78fa66e3 n/a (libgtk-3.so.0)
                                              #15 0x00007f8f78f57f45 n/a (libgtk-3.so.0)
                                              #16 0x00007f8f78fab8bd n/a (libgtk-3.so.0)
                                              #17 0x00007f8f78fb05c8 n/a (libgtk-3.so.0)
                                              #18 0x00007f8f78f5a8d2 n/a (libgtk-3.so.0)
                                              #19 0x00007f8f791cd2f0 n/a (libgtk-3.so.0)
                                              #20 0x00007f8f78fa65ff gtk_container_propagate_draw (libgtk-3.so.0)
                                              #21 0x00007f8f78fa66e3 n/a (libgtk-3.so.0)
                                              #22 0x00007f8f78f57f45 n/a (libgtk-3.so.0)
                                              #23 0x00007f8f78fab8bd n/a (libgtk-3.so.0)
                                              #24 0x00007f8f78fb05c8 n/a (libgtk-3.so.0)
                                              #25 0x00007f8f78f5a8d2 n/a (libgtk-3.so.0)
                                              #26 0x00007f8f791cd2f0 n/a (libgtk-3.so.0)
                                              #27 0x00007f8f78fa65ff gtk_container_propagate_draw (libgtk-3.so.0)
                                              #28 0x00007f8f78fa66e3 n/a (libgtk-3.so.0)
                                              #29 0x00007f8f791db32f n/a (libgtk-3.so.0)
                                              #30 0x00007f8f79072bfc n/a (libgtk-3.so.0)
                                              #31 0x00007f8f791c0512 n/a (libgtk-3.so.0)
                                              #32 0x00007f8f77581a4d g_closure_invoke (libgobject-2.0.so.0)
                                              #33 0x00007f8f77594bca n/a (libgobject-2.0.so.0)
                                              #34 0x00007f8f7759d081 g_signal_emit_valist (libgobject-2.0.so.0)
                                              #35 0x00007f8f7759e130 g_signal_emit (libgobject-2.0.so.0)
                                              #36 0x00007f8f791cd503 n/a (libgtk-3.so.0)
                                              #37 0x00007f8f791d6893 n/a (libgtk-3.so.0)
                                              #38 0x00007f8f79071c0a gtk_main_do_event (libgtk-3.so.0)
                                              #39 0x00007f8f78b81526 n/a (libgdk-3.so.0)
                                              #40 0x00007f8f78b91bcb n/a (libgdk-3.so.0)
                                              #41 0x00007f8f78b92e29 n/a (libgdk-3.so.0)
                                              #42 0x00007f8f78b93029 n/a (libgdk-3.so.0)
                                              #43 0x00007f8f77581a4d g_closure_invoke (libgobject-2.0.so.0)
                                              #44 0x00007f8f77594e40 n/a (libgobject-2.0.so.0)
                                              #45 0x00007f8f7759d6f6 g_signal_emit_valist (libgobject-2.0.so.0)
                                              #46 0x00007f8f7759e130 g_signal_emit (libgobject-2.0.so.0)
                                              #47 0x00007f8f78b8ac5a n/a (libgdk-3.so.0)
                                              #48 0x00007f8f78b75843 n/a (libgdk-3.so.0)
                                              #49 0x00007f8f772a7cb3 n/a (libglib-2.0.so.0)
                                              #50 0x00007f8f772a71d6 g_main_context_dispatch (libglib-2.0.so.0)
                                              #51 0x00007f8f772a75b1 n/a (libglib-2.0.so.0)
                                              #52 0x00007f8f772a78e2 g_main_loop_run (libglib-2.0.so.0)
                                              #53 0x00007f8f79070dcf gtk_main (libgtk-3.so.0)
                                              #54 0x00007f8f74784d22 n/a (libHSgi-gtk-3.0.23-J49TgmeR4Ha3tFtwazpVcU-ghc8.4.3.so)
```

**Comment by LeifW** [comment]
Running `bt` after a crash in gdb give me:
```
[New Thread 0x7fffdc7b0700 (LWP 2580)]
[New Thread 0x7fffdbfaf700 (LWP 2581)]
[New Thread 0x7fffdb7ae700 (LWP 2582)]
[New Thread 0x7fffdafad700 (LWP 2583)]
[New Thread 0x7fffd96bc700 (LWP 2584)]
[New Thread 0x7fffd8ebb700 (LWP 2585)]
[New Thread 0x7fffc3fff700 (LWP 2586)]
[New Thread 0x7fffc37fe700 (LWP 2587)]
Got null pixbuf for info ItemInfo {itemServiceName = BusName ":1.48", itemServicePath = ObjectPath "/StatusNotifierItem", iconTitle = "redshift-gtk", iconName = ":1.48", iconThemePath = Nothing, iconPixmaps = [], menuPath = Nothing}
Got null pixbuf for info ItemInfo {itemServiceName = BusName ":1.48", itemServicePath = ObjectPath "/StatusNotifierItem", iconTitle = "redshift-gtk", iconName = ":1.48", iconThemePath = Nothing, iconPixmaps = [], menuPath = Nothing}

Thread 8 "taffybar-linu:w" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc3fff700 (LWP 2586)]
0x00007ffff7e21a35 in ?? () from /usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so
(gdb) bt
#0  0x00007ffff7e21a35 in  () at /usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so
#1  0x00007ffff7e1eadd in  () at /usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so
#2  0x00007ffff7e3dbea in  () at /usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so
#3  0x00007ffff7e44f8a in  () at /usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so
#4  0x00007ffff7e458e4 in  () at /usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so
#5  0x00007ffff7e28b74 in  () at /usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so
#6  0x00007ffff7e29b71 in  () at /usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so
#7  0x00007ffff7e2ab2c in  () at /usr/lib/ghc-8.4.3/rts/libHSrts_thr-ghc8.4.3.so
#8  0x00007fffe5079075 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff645353f in clone () at /usr/lib/libc.so.6
(gdb) 
```

**Comment by IvanMalison** [comment]
huh, well thats pretty useless. Did you compile with -g and -debug?

**Comment by srhb** [comment]
Is this better?
```
#0  0x000000000040da65 in evacuate1 ()
#1  0x0000000000756681 in scavenge_stack ()
#2  0x0000000000756be6 in scavenge_one ()
#3  0x0000000000757bad in scavenge_loop1 ()
#4  0x000000000074e482 in scavenge_until_all_done ()
#5  0x000000000074edd4 in GarbageCollect ()
#6  0x000000000073f6aa in scheduleDoGC ()
#7  0x000000000074067a in schedule ()
#8  0x0000000000740dcc in scheduleWorker ()
#9  0x00007ffff2aa75a7 in start_thread ()
   from /nix/store/2qgjpsn1zkf0clvrrjympwf6ar2dx83r-glibc-2.27/lib/libpthread.so.0
#10 0x00007ffff2db122f in clone () from /nix/store/2qgjpsn1zkf0clvrrjympwf6ar2dx83r-glibc-2.27/lib/libc.so.6
```

**Comment by srhb** [comment]
Looks like I get different results though...

```
#0  0x000000000076d75f in eval_thunk_selector ()
#1  0x000000000040bedd in scavenge_block1 ()
#2  0x00000000007593df in scavenge_loop1 ()
#3  0x000000000074fd82 in scavenge_until_all_done ()
#4  0x00000000007506d4 in GarbageCollect ()
#5  0x0000000000740faa in scheduleDoGC ()
#6  0x0000000000741851 in schedule ()
#7  0x00000000007426a1 in scheduleWaitThread ()
#8  0x0000000000535ebd in zdgizmglibzm2zi0zi17zmJqMS4SqmLMDKmcjEiFsIfyzdGIziGLibziCallbackszdgizzmglibzzm2zzi0zzi17zzmJqMS4SqmLMDKmcjEiFsIfyzuGIzziGLibzziCallbackszumkzzuSourceFunc ()
#9  0x00007ffff6e77be0 in gdk_threads_dispatch ()
   from /nix/store/vxzxhz6m2cg5rw8z7iybph5hrgaaf9h0-gtk+3-3.22.30/lib/libgdk-3.so.0
#10 0x00007ffff5584db5 in g_main_context_dispatch ()
   from /nix/store/pb0fid3fvvpjkkd38pifgs18anfps8r5-glib-2.56.0/lib/libglib-2.0.so.0
#11 0x00007ffff5585180 in g_main_context_iterate.isra ()
   from /nix/store/pb0fid3fvvpjkkd38pifgs18anfps8r5-glib-2.56.0/lib/libglib-2.0.so.0
#12 0x00007ffff5585492 in g_main_loop_run ()
   from /nix/store/pb0fid3fvvpjkkd38pifgs18anfps8r5-glib-2.56.0/lib/libglib-2.0.so.0
#13 0x00007ffff736f4e5 in gtk_main () from /nix/store/vxzxhz6m2cg5rw8z7iybph5hrgaaf9h0-gtk+3-3.22.30/lib/libgtk-3.so.0
#14 0x00000000004bcd95 in ?? ()
#15 0x0000000000000000 in ?? ()
```

**Comment by PierreR** [comment]
I am not using the battery widget and I can reliabily get a segmentation fault.

Within a virtualbox, I just need to go full screen and taffybar will die:

```
(taffybar-linux-x86_64:1241): Gtk-WARNING **: 18:09:21.392: Theme parsing error: gtk.css:7416:12: Expected a string.
Directory does not exist: /nix/var/nix/profiles/default/share
Directory does not exist: /etc/profiles/per-user/vagrant/share
Directory does not exist: /usr/local/share
Directory does not exist: /usr/share
[1]    1241 segmentation fault  taffybar
```
This makes it useless and is forcing me to go on using `taffybar-0.4.6` for now. My biggest worry is that Taffybar 3.x is going to be the default version in the next stable nixos 18.09.

**Comment by PierreR** [comment]
I have removed the `tray` widget. Still get the segmentation fault even if I have to go from full screen and  back a couple of times to get it.

**Comment by IvanMalison** [comment]
@PierreR The tray widget should have nothing to do with it. It's only the battery widget that causes the issue.

**Comment by IvanMalison** [comment]
@PierreR Are you using xmonad?



> My biggest worry is that Taffybar 3.x is going to be the default version in the next stable nixos 18.09.

This really isn't such a big deal. You can just copy the 0.4.6 deriviation (Why not simply go back to 1.0 or 2.0 for example) into your own custom files to make things work (I can help you with this if it really does become an issue).

The other thing you can do is compile taffybar with ghc-8.2 which should not be too hard with nix.

With all of that said, I'm going to look in to this issue as it also afflicts me.

**Comment by PierreR** [comment]
@IvanMalison Thanks for your help. In my case I don't use the battery widget at all (and taffybar is compiled with  `ghc-8.4.3`.  [Here](https://lpaste.net/911320450221473792) is my config. Is it certain that the problem is related to  `ghc-8.4` ?

**Comment by LeifW** [comment]
I'm guessing this was from https://ghc.haskell.org/trac/ghc/ticket/14346 which affected GHC 8.4.1, 8.4.2, and 8.4.3. I don't get crashes when running a higher version of GHC.

**Comment by IvanMalison** [comment]
Okay, I'm going to close as fixed then. Perhaps we should add something about old versions of ghc in the README?
